/*
 * Copyright (C) 2008 The Guava Authors
 * Copyright (C) 2023-2025 Mangala Wallet
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Modified from original source: https://github.com/google/guava
 */

package com.google.common.kotlin.base

import kotlin.jvm.JvmStatic

//import java.util.Arrays

/**
 * Helper functions that can operate on any `Object`.
 *
 *
 * See the Guava User Guide on [writing
 * `Object` methods with `ObjectsG`](http://code.google.com/p/guava-libraries/wiki/CommonObjectUtilitiesExplained).
 *
 * @author Laurence Gonsalves
 * @since 2.0 (imported from Google Collections Library)
 */
object ObjectsG {
    /**
     * Determines whether two possibly-null objects are equal. Returns:
     *
     *
     *  * `true` if `a` and `b` are both null.
     *  * `true` if `a` and `b` are both non-null and they are
     * equal according to [Object.equals].
     *  * `false` in all other situations.
     *
     *
     *
     * This assumes that any non-null objects passed to this function conform
     * to the `equals()` contract.
     *
     *
     * **Note for Java 7 and later:** This method should be treated as
     * deprecated; use [java.util.Objects.equals] instead.
     */
    @JvmStatic
    fun equal(a: Any?, b: Any?): Boolean {
        return a === b || a != null && a == b
    }

    /**
     * Generates a hash code for multiple values. The hash code is generated by
     * calling [Arrays.hashCode]. Note that array arguments to
     * this method, with the exception of a single Object array, do not get any
     * special handling; their hash codes are based on identity and not contents.
     *
     *
     * This is useful for implementing [Object.hashCode]. For example,
     * in an object that has three properties, `x`, `y`, and
     * `z`, one could write:
     * <pre>   `public int hashCode() {
     * return ObjectsG.hashCode(getX(), getY(), getZ());
     * }`</pre>
     *
     *
     * **Warning:** When a single object is supplied, the returned hash code
     * does not equal the hash code of that object.
     *
     *
     * **Note for Java 7 and later:** This method should be treated as
     * deprecated; use [java.util.ObjectsG.hash] instead.
     */
    fun hashCode(vararg objects: Any?): Int {
        return objects.contentHashCode()
    }
}
