plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
}

publishing {
    Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())

    publications {
        release(MavenPublication) {
            groupId = 'com.mangala.wallet.browser'
            artifactId = project.name
            version = '1.0'

            afterEvaluate {
                from components.release
            }
        }
    }
    repositories {
        mavenLocal()
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/MangalaLabs/mangala-dependencies")
            credentials {
                username = properties.getProperty("GITHUB_ACTOR")
                password = properties.getProperty("GITHUB_TOKEN")
            }
        }
    }
}

apply from: "$rootProject.projectDir/gradle/android-library.gradle"

dependencies {
    implementation "com.mangala.wallet.browser:common:1.1"
    implementation "com.mangala.wallet.browser:autofill-api:1.0"
    implementation "com.mangala.wallet.browser:secure-storage-api:1.0"

    implementation libs.androidx.core.ktx
    implementation("androidx.appcompat:appcompat:1.4.2")
    implementation libs.kotlinx.coroutines.core
    implementation "com.google.android.material:material:1.6.1"

    implementation libs.timber

    // Testing dependencies
//    testImplementation Testing.junit4
//    testImplementation AndroidX.test.ext.junit
//    testImplementation Testing.robolectric
//    testImplementation (KotlinX.coroutines.test) {
//        // https://github.com/Kotlin/kotlinx.coroutines/issues/2023
//        // conflicts with mockito due to direct inclusion of byte buddy
//        exclude group: "org.jetbrains.kotlinx", module: "kotlinx-coroutines-debug"
//    }
}

android {
    namespace 'com.mangala.autofill.store'
}