plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'maven-publish'
}

publishing {
    Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())

    publications {
        release(MavenPublication) {
            groupId = 'com.mangala.wallet.browser'
            artifactId = project.name
            version = '1.0'

            afterEvaluate {
                from components.release
            }
        }
    }
    repositories {
        mavenLocal()
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/MangalaLabs/mangala-dependencies")
            credentials {
                username = properties.getProperty("GITHUB_ACTOR")
                password = properties.getProperty("GITHUB_TOKEN")
            }
        }
    }
}

apply from: "$rootProject.projectDir/gradle/android-library.gradle"

dependencies {
    implementation "com.mangala.wallet.browser:app-build-config-api:1.0"
    implementation "com.mangala.wallet.browser:di:1.0"
    implementation "com.mangala.wallet.browser:common:1.1"
    implementation "com.mangala.wallet.browser:common-ui:1.0"
    implementation "com.mangala.wallet.browser:autofill-api:1.0"
    implementation "com.mangala.wallet.browser:secure-storage-api:1.0"
    implementation "com.mangala.wallet.browser:device-auth-api:1.0"
    implementation "com.mangala.wallet.browser:browser-api:1.0"
    implementation "com.mangala.wallet.browser:autofill-store:1.0"

    implementation("androidx.appcompat:appcompat:1.4.2")
    implementation "com.google.android.material:material:1.6.1"
    implementation("androidx.constraintlayout:constraintlayout:2.1.0")

    implementation libs.kotlinx.coroutines.core
    implementation "androidx.fragment:fragment-ktx:1.5.0"
    implementation "androidx.webkit:webkit:1.4.0"

    implementation "com.squareup.retrofit2:converter-moshi:2.9.0"
    implementation libs.androidx.core.ktx
    implementation("androidx.work:work-runtime-ktx:2.7.1")

    implementation libs.timber

    // Testing dependencies
//    testImplementation "org.mockito.kotlin:mockito-kotlin:_"
//    testImplementation Testing.junit4
//    testImplementation AndroidX.core
//    testImplementation AndroidX.test.ext.junit
//    testImplementation "androidx.test:runner:_"
//    testImplementation Testing.robolectric
//    testImplementation CashApp.turbine
//    testImplementation "org.jetbrains.kotlin:kotlin-reflect:_"
//
//    implementation "com.mangala.wallet.browser:common-test:1.0"
//
//    testImplementation (KotlinX.coroutines.test) {
//        // https://github.com/Kotlin/kotlinx.coroutines/issues/2023
//        // conflicts with mockito due to direct inclusion of byte buddy
//        exclude group: "org.jetbrains.kotlinx", module: "kotlinx-coroutines-debug"
//    }

}

android {
    namespace 'com.mangala.autofill.impl'
}

android {
    lintOptions {
        baseline file("lint-baseline.xml")
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    buildFeatures {
        dataBinding true
    }
}

