plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
}

publishing {
    Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())

    publications {
        release(MavenPublication) {
            groupId = 'com.mangala.wallet.browser'
            artifactId = project.name
            version = '1.0'

            afterEvaluate {
                from components.release
            }
        }
    }
    repositories {
        mavenLocal()
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/MangalaLabs/mangala-dependencies")
            credentials {
                username = properties.getProperty("GITHUB_ACTOR")
                password = properties.getProperty("GITHUB_TOKEN")
            }
        }
    }
}

apply from: "$rootProject.projectDir/gradle/android-library.gradle"

dependencies {
    implementation "com.mangala.wallet.browser:di:1.0"
    implementation "com.mangala.wallet.browser:common:1.1"
    implementation "com.mangala.wallet.browser:feature-toggles-api:1.0"

    implementation libs.kotlin
    implementation("androidx.appcompat:appcompat:1.4.2")
    implementation "com.google.android.material:material:1.6.1"
    implementation("androidx.constraintlayout:constraintlayout:2.1.0")
    implementation libs.androidx.core.ktx

    // Testing dependencies
//    implementation "com.mangala.wallet.browser:common-test:1.0"
//    testImplementation Testing.junit4
}

android {
    namespace 'com.mangala.feature.impl'
}